### ISSUE TITLE
Password Recovery

### ISSUE THREAD

**Issue by bernoulliMukuna21** [kingshire-group/user-service#11]
This ticket covers the efforts needed to complete the work for a user (client/kinglancer) to recover their forgotten password. If the email is connected to a Google signup, a password should just be added to their account. So, when they sign in, they can either go through Google or just use their password on our site. The link recovery link sent should last 1 hour

**Comment by rahulnpadalkar** [comment]
The reset password link never expires
Password recovery only for email signups
